### ISSUE TITLE
[TODO] Create developer documentation 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#102]
To help facilitate new contributors to contribute to our project, we need to create documentation on:

- how to clone or fork the project 
- installing the project client and server
- creating the database and environment variables
- setting up the project in ediors/ides
- how to submit PR's
- basic git usage
- how to start the server, client and database 
- how to run lint and prettier the code
- how to run tests
- list of client and server dependencies
- links to documentation for dependencies 
- links to documentation for React
- link to CONTRIBUTING.md doc

This should also exist in the CodeBooker GitHub Wiki which is clone-able as a separate project and uses markdown files.

**Comment by jchansen925** [comment]
Hi, I'm newish tech writer looking to get more documentation experience. I'd be happy to help with any of the above documentation tasks. I have some experience with JavaScript ES5/ES6/ES7 as wells as git, Angular etc. If you are interested, please get back to me with next steps. Thanks, 

John

**Comment by gbowne1** [comment]
Hi @jchansen925 

I started creating some basic documentation, but its not that solid.   Feel free to work on it and include the things above.

I think the best way is to put the majority of the documentation in the /docs folder as markdown.  

I also think a great addition to this is to use the GitHub wiki which is cloneable at `git clone https://github.com/gbowne1/codebooker.wiki.git` and you can make all the files in markdown and make separate files for each heading.

**Comment by jchansen925** [comment]
Hi @gbowne1 .  Thanks for the reply, and cloning the GitHub wiki and making a markdown file for each heading is a good start. I'll start this process tomorrow and get a placeholder/starter page for each heading beginning tomorrow. 

John

**Comment by gbowne1** [comment]
Alright,  @jchansen925, Feel free to ask questions  here or in Discussions. Myself and or @LOGESH-B can answer them. 

The main objective is to support a developer to get started easily working on this project. Later on the documentation can be elaborated on with more details such as editor specifics, language translations,  etc..

**Comment by jchansen925** [comment]
@gbowne1 Thanks, will be cloning the wiki today and starting on the markdown files.

**Comment by jchansen925** [comment]
@gbowne1 

Hi, I have forked this repo and made docs_update branch there. I have made .md files for this list of topics above-- how to clone or fork the project...

I am trying to commit my changes using HTTP, but am getting 403 errors I can't seem to get around, should I use SSH instead?

**Comment by jchansen925** [comment]
@gbowne1 

These are the errors I am getting: johnhansen@Johns-MacBook-Pro docs % git commit --all 
[master 031a03e] Added fork and clone instructions with images
 5 files changed, 57 insertions(+)
 create mode 100644 docs/CreateFork.png
 create mode 100644 docs/CreateForkBtn.png
 create mode 100644 docs/ForkClone.md
 create mode 100644 docs/ForkedBranch.png
 create mode 100644 docs/fork.png
johnhansen@Johns-MacBook-Pro docs % git push --all
Username for 'https://github.com': jhansen925
Password for 'https://jhansen925@github.com': 
remote: Permission to jchansen925/codebooker.git denied to jchansen925.
fatal: unable to access 'https://github.com/jchansen925/codebooker.git/': The requested URL returned error: 403

**Comment by LOGESH-B** [comment]
> @gbowne1
> 
> These are the errors I am getting: johnhansen@Johns-MacBook-Pro docs % git commit --all [master 031a03e] Added fork and clone instructions with images 5 files changed, 57 insertions(+) create mode 100644 docs/CreateFork.png create mode 100644 docs/CreateForkBtn.png create mode 100644 docs/ForkClone.md create mode 100644 docs/ForkedBranch.png create mode 100644 docs/fork.png johnhansen@Johns-MacBook-Pro docs % git push --all Username for 'https://github.com': jhansen925 Password for 'https://jhansen925@github.com': remote: Permission to jchansen925/codebooker.git denied to jchansen925. fatal: unable to access 'https://github.com/jchansen925/codebooker.git/': The requested URL returned error: 403

Hii @jchansen925 
This may help you
https://github.com/trilbymedia/grav-plugin-git-sync/issues/39
