### ISSUE TITLE
[TODO] Style the login and register page

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#113]
The Login.jsx and Register.jsx are completely unstyled pages

Style them using the Login.css and Register.css

**Comment by kabszac** [comment]
Is there any specific design to follow?

**Comment by gbowne1** [comment]
@kabszac No, there is no design to follow.

**Comment by kabszac** [comment]
can I work on this?

**Comment by gbowne1** [comment]
Yes @kabszac
