### ISSUE TITLE
[BUG] Clicking ->] Logout button in the (R) user menu should redirect to / or /login

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#120]
With the Login working correctly, and the UI styled for Login and Register, 

The Logout function should:

- Kill the session, etc.
- and Redirect the user to / or /login

It's hard to tell if the logout function actually works as there is no visual clue that you're logged out.

Add a toast, popper, snackbar or alert  to tell the user that he is either logged in or logged out.  

Also the Login should welcome the user by name or user id.

**Comment by ratishjain12** [comment]
I can fix this issue can you assign it to me @gbowne1 

I will toast menus and redirecting functionality

**Comment by gbowne1** [comment]
Ok I will assign this to you @ratishjain12
