### ISSUE TITLE
[Dev Feat] Add .eslintignore and .prettierignore files

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#122]
To save prettifying and ESLint's linting time, we should add .prettierignore and .eslintignore files.

We do not need Prettier and ESLint messing with stuff like the code that ships when create react app runs like the /public folder and index.css and reportWebVitals.js  (other than App.js) and also node_modules can be excluded.

Keep in mind that these files use .gitignore syntax.

**Comment by akshitarora921** [comment]
@gbowne1 Can I take this?

**Comment by gbowne1** [comment]
Yes you can @akshitarora921. I will assign you.
