### ISSUE TITLE
[FEAT] Add a Help feature

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#123]
Add a help feature.

We have a Help button in the (R) user icon button dropdown menu.

 It does not have anything associated with it.

**Comment by BlackBond06** [comment]
Hi @gbowne1 please assign this issue to me. Also, explain what the expected functionality of this feature is.

**Comment by gbowne1** [comment]
@BlackBond06 

This feature basically is a help system for users who may be having issues using the app, and may provide the user with contact information.  It would describe what to do when users have issues with the app. It may also include some directions/instructions on using the app.  It would be available by using the icon in the dropdown menu under the (R) user icon/avatar

**Comment by BlackBond06** [comment]
@gbowne1 
Cool. I'm thinking we can use A.I for this one. Like those automated personal assistants on Web sites. We can give it answers to common problems we think user will come across. But if a user ask a question that isn't covered in the answers we supplied, we can just display an email form and ask that the user describ the problem and mail to the support team. What do you think ?

**Comment by gbowne1** [comment]
I think thats a bit beyond the scope just yet.  Most problems could be described easily in a page.  Could just breadcrumb that page. We don't have users yet, so ideally the best way would be to have a small number of users test the application and describe the problems they had.  We will have to collect some data and try and use it ourselves to come up with some good solutions.  So, maybe it's best for now to provide just a form email and support team contact.  Add Formik and Yup to do all the form and form validation stuff.

**Comment by BlackBond06** [comment]
I totally agree. I will begin working on it today. Will formik handle the actual email sending or do I have to use nodemailer ?

**Comment by gbowne1** [comment]
nodemailer will handle emails just fine. it's already installed.  Its handling password reset etc functionality.   Formik and Yup handle forms really well.

AI is fine, but it's overkill, at least for now.  We need to collect the data on problems people  are having..  but also provide adequate documentation on how to use the App.  Later on we can write some FAQ's.

**Comment by gbowne1** [comment]
https://www.npmjs.com/package/formik
https://formik.org

https://www.npmjs.com/package/yup
It's a good really object schema validatior..

**Comment by BlackBond06** [comment]
Okay. Thanks for the resources

**Comment by gbowne1** [comment]
yvw! I found the videos helpful.  I can help with Yup.

**Comment by BlackBond06** [comment]
Hi @gbowne1 I have been going through the support page for a couple of popular websites for inspiration and a common feature I noticed, is  the presence of a search bar just below the top of the support page, where users can enter their query for help. I know at this stage of the app, the search bar may not do anything since we don't have data on the problems user have, but should I include it in the design in addition to the form, since it is a common feature of support pages ?

**Comment by gbowne1** [comment]
that is a great idea.  I had not thought of that.  This is why I started this project. People usually have way better ideas for designs and features than me :-} and I agree this sort of thing would be handy.

**Comment by BlackBond06** [comment]
Hi @gbowne1, I need clarification about the form in help feature. Should it just have one input element for the user's email and a textarea for the query description ? or is there any other information we might need from the user?

**Comment by BlackBond06** [comment]
This is what I have so far: 

https://github.com/gbowne1/codebooker/assets/100074330/b961e6af-2968-47df-845a-6c906edf7028

**Comment by gbowne1** [comment]
@BlackBond06 I would think email, username and a text area would be great. Eventually we can replace with a more robust system with a scenario based help system including all the 'What to do if x or y happens' type system.  That looks great.

**Comment by BlackBond06** [comment]
So I can proceed with what I have so far ?

**Comment by gbowne1** [comment]
Yes you can.

**Comment by BlackBond06** [comment]
Hi @gbowne1, Aside sending the query from the form to the codebooker mail address, should it be saved in the db as well ?

**Comment by gbowne1** [comment]
@BlackBond06 

Yes at least in my opinion it should be saved in the db.

**Comment by BlackBond06** [comment]
I thought so. I created a supportModel schema with the following properties (subject to change):
- userId
- description
- status
- createdAt

What are your thoughts ? Are there  other properties I should add ?

**Comment by gbowne1** [comment]
@BlackBond06 I think that is a great start.  We can always iterate.

**Comment by BlackBond06** [comment]
Cool. I should make a PR for this feature by tomorrow. I'm almost done.

**Comment by gbowne1** [comment]
Alright, looking forward to the PR.

No rush at all.  I am all for quality over quantity.  

I will be posting some contributor guidance over in the Discussion tab, now that we have a small number of active contributors and also a couple collaborators as well.

**Comment by BlackBond06** [comment]
Hi @gbowne1, @LOGESH-B 

I have opened a PR for the Help/Support feature, please review.

**Comment by gbowne1** [comment]
It has a merge conflict with App.js. 
@BlackBond06 

I will review

**Comment by BlackBond06** [comment]
Oh, really ?. I await your review.

**Comment by gbowne1** [comment]
Yes, it does. It has a merge conflict with App.js. as it is right now would be unable to merge unless App.js is fixed.  I will review in a little while. Am currently away from my PC.  Thanks.
