### ISSUE TITLE
[FEAT] Add a Forgot Password feature.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#126]
One thing that doesn't yet exist is the UI for the Forgot Password feature of the Login page.  We already have the route..
it is /forgot-password.  

Here's some ideas:

- Create an API endpoint on the server to handle the forgot password request. 

- This endpoint should generate a unique token and send a password reset link to the user's email address. You can use a package like nodemailer to send the email.

- Create a frontend page for the forgot password feature. This page should include a form where the user can enter their email address. When the form is submitted, it should make a request to the API endpoint.

- When the user clicks on the password reset link in their email, it should direct them to a password reset page on the frontend.

- This page should include a form where the user can enter a new password.

- Create another API endpoint on the server to handle the password reset request. This endpoint should validate the token sent in the request and update the user's password in the database

I would probably use the packages `nodemailer`, `jsonwebtoken`, `bcrypt`, `axios`, `express` and `mongoose`.

**Comment by BlackBond06** [comment]
Hi @gbowne1 can you please assign this issue to me?

**Comment by gbowne1** [comment]
Sure @BlackBond06

**Comment by BlackBond06** [comment]
Hi @gbowne1, I have made a PR for the issue, please review and if there is anything more I can do, I'm more than happy to help.

**Comment by gbowne1** [comment]
@BlackBond06 I reviewed this PR and looks great.  

Thanks for the opportunity to review your PR.  

Waiting on @LOGESH-B to review and approve

Feel free to work on any other issues in the issues tab.

**Comment by BlackBond06** [comment]
Thank you @gbowne1 and @LOGESH-B for your review and guidance. I'll begin working on issue #128 right away.

**Comment by gbowne1** [comment]
Glad to be of help @BlackBond06.

Keep in mind a few things:

- 2 successful reviews in order to get merged

- Am currently considering 5 miniumum successful merges in order to be considered for being invited to be a collaborator

- Make sure you run the `npx eslint --fix .` and `npx prettier --write .` commands before you commit and PR and clean up anything found.

If you need anything you can always make an issue or a discussion and we can discuss any issues.  And feel free to report bugs, errors, warnings.. especially any in browser console or dev tools.

Thanks
