### ISSUE TITLE
[Feature] Adding new book to Db

### ISSUE THREAD

**Issue by LOGESH-B** [gbowne1/codebooker#128]
Now the data are from the data.json.As we initialized the db,  getting the project to next level by using the db as storage insted of staic data file
- [ ] Implementing  adding new book to db

**Comment by BlackBond06** [comment]
Hi @LOGESH-B, is this issue still open? If it is, can be assigned to it?

**Comment by gbowne1** [comment]
I think it's still open @BlackBond06 and I am sure you could work on it.  I will assign you anyhow.

Right now we are relying on the data in the .json file for the data that actually appears in the table that you see in the app.

**Comment by LOGESH-B** [comment]
Hii @BlackBond06 
You can look at this disscussion for better view
https://github.com/gbowne1/codebooker/discussions/130#discussion-5503121

**Comment by BlackBond06** [comment]
okay thanks @LOGESH-B, I'll do that. Please review the PR I made for #126

**Comment by BlackBond06** [comment]
Hi @gbowne1 I'm just going through the code that uses the data from data.json to populate the UI on the home page. I have a few questions : 
1. What would be the default state of the Home component be if all the books were removed from it (I simulated a case where I deleted all books in the Home component, and the icon to add books went away, is this behavior intentional? ) ?

2. On page load, assuming we did not have data from the json file and in the db, should the home component show the add book icon for users to add books to the db (this is still related to the first question)?

**Comment by gbowne1** [comment]
1. I intended the app to be able to have users be able to:

Add books to their own library from whatever books are on their shelves easily like hand entry or barcodes or isbn number 

Added books to the main/global scope so books appear in the main view 

Be able to add books from both the main/global scope and their own library

Access their own library of added books from the [Library] button in the left sidenav.

Able to sort books in categories from the left sidenav based on what the books categories are set to

2. I am not sure. Am open to thoughts about this part of the UI based upon 1.

**Comment by BlackBond06** [comment]
First off, I think adding books through scanning the isbn (that's what you mean right?) is a very cool feature and we should pursue it. Is there la ibrary we can use to achieve this? 

As for a user adding books to the global scope and  personal library, I'm thinking each book a user adds should have a userId property that ties it to the user. So when a user adds a book, it goes to the books collections with the id of the user.Now when the page loads  it pulls all the books from the books collection in the dB and displays it on the global scope. But in the user personal library, only the book(s) which match the userId is displayed, else the option to add a book by hand entry or isbn scanning is displayed.

Also, I think we should show the various options (hand entry and isbn scanning) to add a book if there is no book in the dB.

**Comment by gbowne1** [comment]
@BlackBond06 

I totally agree with those ideas.  I added the react-barcode library a while back so its there to use already.  Scanning EAN-13 barcodes only copy in the ISBN number, if not, they are Code 39 barcodes, and we would have to figure out how to 
Scanning the barcode would fill out the ISBN field.  I don't know about autofill/autocompleting the rest.  I assume once we get enough books in the dB, it will be less and less work.

Ideally we would become our own data source for books on coding/programming/software development and related topics.  

Some books on coding/programming/software development are also textbooks meant for education/schools/college/university. So there should be also way to discern what is a textbook.  Could be useful for schools and teachers/professors.

Also ideally any book that would get added to the users own bookshelf/library would get added to the global scope library if it is not already in the library.  

The search bar barely works too.  

I also found it hard to add categories to books from the Add Book UI.  As it is, even if you were to add the categorry to an individual new book, it doesn't show up.  

There should be an edit book function too.  If a user missed entering information on a book, say year, should be able to edit a book

**Comment by BlackBond06** [comment]
Yea I noticed the category doesn't get added too. And why doesn't the  book model have a category property?

I'll just try and get a prototype running with the ideas we discussed so we can test and see what we can add or remove.

**Comment by gbowne1** [comment]
@BlackBond06 

I don't know why it doesn't.  I noticed the prop was missing.  I just noticed that you could enter the category but it doesn't show up once added.  Do we need to add that issue?

Clicking on the categories on the left sidenav/drawer should let the UI switch so that it only displays books in that context and category.  User clicks on Web Development category on the drawer and it should only show the books on Web Development whether they be in their library or global scope library.

I think it's coming along pretty nicely. Looking forwards to seeing what we can accomplish with this and your prototypes.

**Comment by BlackBond06** [comment]
We would need to update the book model to include the category property as it is a required property. I'll do that tomorrow.

Don't open an issue yet. Let me look into why it doesn't add the category when a book is added.I'll get back to you on that as well.

So clicking on  a particular category on the side nav should do the same thing as searching books in the search bar. Is that what you mean?

**Comment by gbowne1** [comment]
Yeah, the book model may need some work.  I already figured that.

Ok.

Yes thats what I meant.  Might not be the best UI/UX but I thought about ease of access when coming up with features.

**Comment by BlackBond06** [comment]
I just checked the code. I think why the category isn't added to the ui when a book is added is because of the following:

I. There isn't a category state (there is a state for all books property except category)

II. Because there isn't a category state, the addItemToTable function is not checking if the category field has an entry unlike all other fields that it checks for.

III. The bookObj object is therefore not accepting a category entry(It accepts every other field). And so when the new bookObj is spread into the myBooks array, there is no category entry. So even if there is a component for the category field in the UI, the returned data doesn't contain a category entry and so doesn't get displayed.

**Comment by gbowne1** [comment]
Yeah, to me that sounds exactly what's happening.

I don't know why that got overlooked.  We can fix that. Add an issue or I can if you want.

**Comment by BlackBond06** [comment]
Please go ahead. Assign it to me too, I think I can fix it.

**Comment by gbowne1** [comment]
I forgot it's already an issue.. #128 https://github.com/gbowne1/codebooker/issues/128

**Comment by BlackBond06** [comment]
Hi @gbowne1, I have a few suggestions for this Adding-new-book-to-db feature I'm currently working on that I would love to hear your thoughts on:

I think the global scope (home page) should only display all books in the books collection in the db. 

There should be an add book button with a position of fixed, floating maybe at the bottom left (much like where these A.I rep component are placed on websites ), which users can click  and it brings up the add book form modal for users to add a book.

Users should only be able to delete a book they added, either from their personal library or from the global scope. In this case, we would have to remove the delete icons (as it is now) and replace it with an ellipsis, where users can click and access the options to delete or edit a book (again these actions, delete and edit can only be performed if the book was created by the user.)

The library option in the side nav currently doesn't do anything. I think it should be a page. that is, when it is clicked, it should navigate to the user's personal library where the user can access and perform actions (delete, edit etc) on these books

**Comment by gbowne1** [comment]
@BlackBond06 

I like those ideas.

The categories in the left sidenav drawer could ideally be used to sort both global and user library state.

Ideally the app might start with a CodeBooker loading then login or register screen. 

You would only see the entirety of the app once you've done those things.

I'm looking forward to seeing what your idea  are.

I also intend for the app to be a be a bit social where you can share your lists of favorite coding/programming/software development books with others and maybe on other sites, apps and platforms. 

GitHub used to have a reading list secret feature as a repo where you README.md your book lists. My original idea was to enhance that experience for coding and for code/programming streamers and their viewers to be able to share these resources with their audience and in chat.

**Comment by BlackBond06** [comment]
Yea we should totally have a feature to share books with other users   and to other platforms.

I have already began implementing some of those suggestions I made. As soon as I have something tangible I'll make a PR so you can review.

**Comment by BlackBond06** [comment]
hi @gbowne1, @LOGESH-B , I just made a PR for this feature. please review.

**Comment by BlackBond06** [comment]
Also since the 'edition'  property is set to number, please use only number entry else you will get a cast error and the book wont be added.

**Comment by BlackBond06** [comment]
@gbowne1 @LOGESH-B 

I have implemented the requested update on the book action restriction. Now actions such as delete, edit and share is displayed on only books added by the currently logged-in user. Please review.
