### ISSUE TITLE
[TODO] Add a Settings component to the UI 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#13]
Using MUI v5.11.6,

Create a Settings that either opens from the context menu from the UserIcon at the top right of the UI, or on the SideNav component.  You can make it a modal, or use a portion of the view.

This component will control app settings, especially settings for the  screen/view/display/theme and notifications/alerts.Possibly even Accessibility (a11y) settings.

You can boilerplate common application settings so we can iterate though design decisions by the community.

Use the gear icon in icons-material.. as import SettingsIcon from '@mui/icons-material/Settings';

**Comment by k-deepak04** [comment]
i would like to do this and create a PR shortly

**Comment by gbowne1** [comment]
Go for it @k-deepak04

**Comment by k-deepak04** [comment]
Setting button added to the UI @gbowne1 
Issue resolved #20 
Kindly check and merge
![Screenshot (187)](https://user-images.githubusercontent.com/96341431/232208167-7aa0b73a-738a-4a9a-949c-c913ddb679bb.png)
![Screenshot (188)](https://user-images.githubusercontent.com/96341431/232208170-537e88a8-2b55-4869-970f-879853a3d687.png)

**Comment by gbowne1** [comment]
This would actually probably be better if it existed inside an dropdown menu that opens when you click on the User Icon which is currently an R inside a circle.

I can provide a screenshot or links in about 9 hours from now.

That is the way it is in my other React apps in my repos called reactsocialnetwork and also same as AgiliZenti.

**Comment by k-deepak04** [comment]
sure i can do this same thing inside r icon also, i interpreted the above thing as setting icons must be there and on click of that thing should work.
please provides the screenshots, create and assign that issue to me . i would be willing to work on that.

**Comment by gbowne1** [comment]
Will do that as soon as I am back at my PC today @k-deepak04

**Comment by gbowne1** [comment]
Ok @k-deepak04 

Here is the screenshot...
![Screenshot 2023-04-15 at 14-06-02 React Social Media App](https://user-images.githubusercontent.com/47549872/232253170-57c14d1c-e60a-4ed8-89a5-2bca9d6898ea.png)

This should be the style for the dropdown menu coming off of the bottom of the circle with the R. (User Icon).

This is how it was done in this app.  https://github.com/gbowne1/reactsocialnetwork and a few others I have.

Let me know if you have any questions.

**Comment by k-deepak04** [comment]
@gbowne1 will try to make it look like this. but caught up in some other imp work.
i would Try to contribute as soon as possible

**Comment by gbowne1** [comment]
No worries at all @k-deepak04. Contribute when you are able to do so.

**Comment by k-deepak04** [comment]
I tried the above link but wasn't able to figure it out.
@gbowne1 will contribute to other things.....and if the burden lessens then will look in this issue again

**Comment by gbowne1** [comment]
That is fine with me.  Thanks for trying.  Plenty of issues and things to work on.

There are  also issues in that anyone can work on: 

https://github.com/gbowne1/reactsocialnetwork
https://github.com/gbowne1/AgiliZenti
https://github.com/gbowne1/gbowne1site_react
