### ISSUE TITLE
[FEAT][TODO] Add TailwindCSS on top of MUI v5

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#131]
I think it would be really nice if we could start implementing Tailwind CSS on top of MUI.

https://mui.com/base-ui/guides/working-with-tailwind-css/

https://www.youtube.com/watch?v=QQIfuMlA6TI

**Comment by BlackBond06** [comment]
Hi @gbowne1, please assign this issue to me.

**Comment by gbowne1** [comment]
Any collaborator and maintainer could theoretically assign themselves to a issue and just to make you aware, that is completely fine with me. I've assigned you this task.  Thank you :)

**Comment by BlackBond06** [comment]
Oh, I didn't know that. Still new to this collaborator thing 🤣.

**Comment by gbowne1** [comment]
It's ok.  You also have direct push access, but I still prefer collaborators do PR's.  

I really need to revise the collaboration/contributing guide.
