### ISSUE TITLE
[TODO] Create actual categories for the Library

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#14]
CodeBooker will have official categories.

These will be:

- Web Development
  - HTML, CSS, JavaScript, etc.
  - Web Design
  
- Languages
  - Python, C, C++, Assembly, C#, JavaScript, Perl, PHP, Typescript, etc.

- Frameworks & Libraries
  - React, Angular, Vue, Next, Nuxt, etc.
  - Microsoft, i.e, .NET, Azure

- Agile/QA/Testing

Add these Categories to the SideNav menu and the table.

**Comment by victor20m** [comment]
@gbowne1 as for your question in https://github.com/gbowne1/codebooker/pull/25:

This is why I added the prop "expandable" on the new sub component. We can treat the main categories as expandable (see the Category button for reference).

However, I would add a "name" prop to MenuButton and change this:

`expandable && expandItem(label);`

for this:

`expandable && expandItem(name);`

If you prefer, you can assign this one to me also.

**Comment by gbowne1** [comment]
Proceed however you like.  I (or you) can create a new issue and assign you to that.  I don't really see the need for that since that would just be work expanding on this particular PR. Either way works for me.

Expandable categories will be good since programming categories and subequent sub-categories are a bit vast in nature.
