### ISSUE TITLE
[BUG] useEffect has a missing dependency

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#143]
After the recent merges and features, I am now getting this warning/error:

[eslint] 
src/pages/Home/Home.jsx
  Line 58:8:  React Hook useEffect has a missing dependency: 'location.state.loggin'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/pages/Home/Home.jsx
  Line 58:8:  React Hook useEffect has a missing dependency: 'location.state.loggin'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

webpack compiled with 1 warning

I thought this may be because login is misspelled `loggin`, but even with correcting the spelling still has a missing dep warning.

**Comment by gbowne1** [comment]
I am also getting location.state is null from the 'Home.jsx` component.

**Comment by ratishjain12** [comment]
I have fixed this in my latest Pull Request for profile page
