### ISSUE TITLE
[FEAT] Add a page for /privacy-policy route 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#149]
Clicking on Read our Privacy Policy goes to an empty route as /privacy-policy.

Create a boilerplate privacy policy.

You can include:

Information Collection: Clearly state what types of personal information you collect from users, such as names, email addresses, or user-generated content.

Purpose of Collection: Explain the purpose for collecting personal information, such as providing personalized book recommendations or improving the app's functionality.

Data Usage: Describe how you use the collected data, such as analyzing user preferences or sending notifications about new book releases.

Data Sharing: Specify if and how you share user data with third parties, such as analytics providers or book publishers. If you do share data, explain the purpose and ensure compliance with applicable laws and regulations.

User Rights: Inform users about their rights regarding their personal information, such as the right to access, correct, or delete their data. Provide instructions on how users can exercise these rights.

Data Security: Describe the measures you take to protect user data from unauthorized access, such as encryption or secure storage practices.

Cookies and Tracking Technologies: If your app uses cookies or other tracking technologies, explain their purpose and provide options for users to manage their preferences.

Legal Compliance: State that you comply with relevant privacy laws and regulations, such as the General Data Protection Regulation (GDPR) or the California Consumer Privacy Act (CCPA).

Updates to the Privacy Policy: Inform users that the privacy policy may be updated periodically and provide a date for the last revision. Notify users of any significant changes and obtain their consent if required.

Contact Information: Provide contact details for users to reach out with privacy-related inquiries or concerns.

**Comment by alienqqe** [comment]
Hello, I'd like to work on this issue.

**Comment by gbowne1** [comment]
Ok @alienqqe

**Comment by alienqqe** [comment]
@gbowne1 Sorry for bothering you but I have some CORS problems while logging in on the dev server.


https://github.com/gbowne1/codebooker/assets/128291891/c4638117-6827-4866-8ff4-55ba70bc7cbd

**Comment by gbowne1** [comment]
@alienqqe 

How far have you gotten with installing and configuring the project? 

You can use MongoDB locally, or use MongoDB Compass or MongoDB Atlas.

That's the wrong authentication anyhow and you will get CORS errors if you don't use the right ones.

By the way, the login information is in the setup.js here:

[setup.js](https://github.com/gbowne1/codebooker/blob/master/src/server/setup/setup.js)

the username is `test`
the email is `test@gmail.com`
the password is `test`

Also in the same folder where `.variable.env` is create a `.env` file and add the following.

MONGO_DB=mongodb://username:password@localhost:27017/codebooker
PORT=3001

change username and password here to whatever you used as your database password and user.

Let me and @LOGESH-B know if you need further assistance.

@LOGESH-B

**Comment by alienqqe** [comment]
@gbowne1 
Now I did everything except Mongo db installation and setup.js running(it throwing auth error) and the login request isn't throwing cors error(now request is timing out). I would appreciate some help with Mongo DB installation.

**Comment by gbowne1** [comment]
@alienqqe 

Mac, Linux or Windows?

here are the MongoDB installation documents:

https://www.mongodb.com/docs/v5.0/administration/install-community/ 

let @LOGESH-B and I know if you have any problems with this.

**Comment by alienqqe** [comment]
@gbowne1 
Done! Thank you a lot!

**Comment by gbowne1** [comment]
Anytime. @LOGESH-B

**Comment by alienqqe** [comment]
Hello again @gbowne1 what email I should write as a contact email in privacy policy?

**Comment by gbowne1** [comment]
You could use an example.com email address. 

Don't have an email set up for this yet.  Pick an address that makes sense.

Although nodemailer package is already set up to do password reset so it could potentially be set up to do another task like policy changes, a lot of apps use a mailer for that.
