### ISSUE TITLE
[TODO][FEATURE] Add a method to handle PDF books on programming/coding?

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#15]
We currently have no way to handle PDF's or eBooks on Programming/Coding, not even a way to upload them or manage them.
Some users may prefer to add their PDF or eBook library of books on programming instead of physical books.

Would this be a good feature?  There might be legal issues with storing books on the server, but could definitely track users PDF and eBooks in this Genre / Category of Programming/Coding.

**Comment by goutham03062001** [comment]
Apart from worrying about legal issues for stroing books. It would be a great feature to keep track of the pdf or ebooks. So that we can able to  keep track that book and it would be very helpful to improve our suggestion feature.

**Comment by gbowne1** [comment]
Yes this is a feature I think could be quite useful @goutham03062001

**Comment by gbowne1** [comment]
Closing as beyond the initial scope of this app
