### ISSUE TITLE
[BUG] ProtectedRoute.jsx gives Uncaught NS_ERROR_ABORT

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#156]
This is the error I get in my console, I mainly see this when I am navigated to the main view at the root route '/' 

Firefox 116 mentions that it is coming from ProtectedRoute.jsx line #5

```jsx
 const token = JSON.parse(localStorage.getItem('token'));
```

Here is the associated error:

```shell
Uncaught NS_ERROR_ABORT: 
    UserAuthenticated ProtectedRoute.jsx:5
    React 11
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6
    Webpack 24
        __webpack_require__
        fn
        js
        factory
        __webpack_require__
        fn
        js
        js
        factory
        __webpack_require__
        fn
        js
        factory
        __webpack_require__
        fn
        js
        factory
        __webpack_require__
        fn
        js
        factory
        __webpack_require__
        <anonymous>
        <anonymous>
```

**Comment by gbowne1** [comment]
I think this issue is resolved.  Not sure. 
I think this 's a protected route problem.   @LOGESH-B @BlackBond06 etc

I want to go through and eliminate issues etc that are completed.

**Comment by BlackBond06** [comment]
I think it has. I don't get the error on both Microsoft Edge and Chrome browsers I haven't tested it on FireFox tho.

**Comment by gbowne1** [comment]
Ok @BlackBond06.  I have not seen this error lately either.  Just wanted to confirm before I close this as completed.

**Comment by gbowne1** [comment]
Closing as completed.
