### ISSUE TITLE
Improve privacy policy page with some styling

### ISSUE THREAD

**Issue by ratishjain12** [gbowne1/codebooker#159]
@gbowne1 I want to improve the overall look and feel of the privacy and policy page

so kindly assign it to me :)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by gbowne1** [comment]
Ok @ratishjain12

**Comment by ratishjain12** [comment]
@gbowne1 sorry for the delay my exams are going on rn so not able to contribute,
Will start contributing to this project in next week or so.

**Comment by ratishjain12** [comment]
@gbowne1 sorry for the delay my exams are going on rn so not able to contribute,
Will start contributing to this project in next week or so.

**Comment by gbowne1** [comment]
@ratishjain12 

No worries, contribute when you're able to. You are very close to being invited to be a collaborator.  Looking forward to reviewing your PR.  Thanks for keeping us updated.

**Comment by ratishjain12** [comment]
@gbowne1 this issue is still open right I am working on this?

**Comment by gbowne1** [comment]
Yes it is still open and I did assign you @ratishjain12

**Comment by BlackBond06** [comment]
@gbowne1 I'll also be working on this issue.

**Comment by BlackBond06** [comment]
@gbowne1 This should be removed from the issues list since it has been merged.

**Comment by gbowne1** [comment]
@BlackBond06 Sorry I forgot to add & link the issue to the PR, which would have closed the issue automatically.

If you create a PR that already has a issue, make sure you add the issue to the PR, which you can do from either the PR or the issue and the issue(s) will be closed on merge.

If there is no issue, I would appreciate a issue being created.

We still have a bunch of browser console issues in Firefox to get through (I still need to look at most of the app in Chrome).
