### ISSUE TITLE
[TODO] Create a method to add or remove or edit books to the users' Library

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#16]
There is currently no way to add books to the library in the UI.

Add a method to add new books to the users library in the UI, using a + icon.  A - or a trashcan icon would work for delete.

There is also no way currently in the UI to edit the row or column data.

**Comment by Yuva0** [comment]
One small suggestion would be to make the database first so that on adding books, it can be directly inserted into the database instead of hardcoding it on using the + icon

**Comment by gbowne1** [comment]
@Yuva0 

Yes, mean we can do a mock database totally.  We are gonna have to mock data anyhow for testing before production. In production I am locally hosting, and that hasnt been done yet.  The UI should be there too.  Database doesn't do much without the actual controls, etc.

**Comment by goutham03062001** [comment]
Can we create our own json object which includes a book properties. So that we can perform add and delete features to that json object. Would like to receive your feedback. Btw, I'm so much interested towards contributing to this project.

**Comment by gbowne1** [comment]
Yes we can do that @goutham03062001
