### ISSUE TITLE
[BUG] Library.jsx has some useEffect issues after today's merge(s).

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#160]
Compiled with warnings.

[eslint] 
src/components/Library/Library.jsx
  Line 337:8:  React Hook React.useEffect has a missing dependency: 'myRows'. Either include it or remove the dependency array. You can also do a functional update 'setMyRows(m => ...)' if you only need 'myRows' in the 'setMyRows' call  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/components/Library/Library.jsx
  Line 337:8:  React Hook React.useEffect has a missing dependency: 'myRows'. Either include it or remove the dependency array. You can also do a functional update 'setMyRows(m => ...)' if you only need 'myRows' in the 'setMyRows' call  react-hooks/exhaustive-deps

webpack compiled with 1 warning

**Comment by BlackBond06** [comment]
Hi @gbowne1, let me resolve this error. I think it came from my last PR

**Comment by BlackBond06** [comment]
@gbowne1 I have made a PR that resolves this issue. Please review.
