### ISSUE TITLE
[BUG] Minor: Greeting notification rendered twice upon successful login

### ISSUE THREAD

**Issue by vktr-r2** [gbowne1/codebooker#170]
**Description**
Upon successful login with any user profile, the user is greeted with a successful login prompt twice.

`toast.success('Welcome! ' + username)` appears to be rendering twice from the Home.jsx component

**To Reproduce**

1. Log into CodeBooker with any existing user
2. Observe toaster notification at top of app.  Notification will appear twice.

**Expected behavior**
User should be greeted by prompt only once upon successful login.

**Screenshots**
<img width="1406" alt="Screenshot 2023-09-11 at 23 44 19" src="https://github.com/gbowne1/codebooker/assets/122321007/cbb39d85-77ea-4ab6-b952-90951b2fc575">

**Reproduced on:**

-   Mac OS Ventura 13.5
-- Google Chrome 116
-- Safari 16.6

**Comment by vktr-r2** [comment]
This should be a quick fix.  Please assign to me if you don't mind

**Comment by gbowne1** [comment]
Yes I noticed this double.  I forgot to add this issue. Thanks for covering it for me.
