### ISSUE TITLE
[Feature Request] Minor: Allow user to submit credentials on return/enter press on keyboard

### ISSUE THREAD

**Issue by vktr-r2** [gbowne1/codebooker#171]
**Opportunity for smoother login flow**
After entering both email and password into the login form, user must either manually click "Sign In" button, or hit tab 3 times on keyboard and then enter to submit credentials.

**Suggested solution**
For convenience and usability purposes, most sites allow users to hit return/enter immediately once credentials are entered to submit the form.

**Comment by vktr-r2** [comment]
Can you assign this to me as well please?

**Comment by gbowne1** [comment]
Ok @vktr-r2. Assigned.

**Comment by vktr-r2** [comment]
[PR 176](https://github.com/gbowne1/codebooker/pull/176) closes this issue.
