### ISSUE TITLE
[TODO] Add a dropdown menu to the User Icon 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#19]
Using MUI v5.11.6, 

There should be a dropdown menu thar appears when you click on the User Icon on right side of the TopBar/TopNav.

This should include access to the Settings, Login and Logout toggle and possibly others like Help and Feedback with their respective icons .

It should apoear off to the bottom right under the User Icon.

This can be its own compnent with custom hooks or useState, useEffect.

**Comment by 777Prabhjot** [comment]
i would love to work on this can i

**Comment by gbowne1** [comment]
Yes you can @777Prabhjot

**Comment by goutham03062001** [comment]
is this issue resolved? If not i'm interested to work on this.

**Comment by gbowne1** [comment]
Yes this is resolved @goutham03062001
