### ISSUE TITLE
[TODO] Add a dark mode/light mode theme toggle 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#2]
Add a dark mode/light mode theme toggle using the Switch toggle in the TopNav.

Light mode theme should use the white and blue, but could be other colors.  

If you build a theme controller, use red, orange, yellow, green, blue, indigo, violet. With possibly a way to let user pick from those colors.

Dark mode theme should be some combination of black, grey, white.

**Comment by k-deepak04** [comment]
i have solved this issue i will create a pr shortly
