### ISSUE TITLE
Title: Feature Request: Custom Axios Hook for Streamlined HTTP Requests

### ISSUE THREAD

**Issue by dev-george-nikolaidis** [gbowne1/codebooker#218]
Hello 

**Feature Description**:
I propose the creation of a custom React hook that utilizes Axios for managing HTTP requests. This hook would aim to standardize the way we make requests and handle different loading states across our application.

**Benefits**:
- **Consistency**: Ensures a uniform approach to making HTTP requests.
- **Efficiency**: Simplifies the codebase by abstracting repetitive logic.
- **Usability**: Enhances the developer experience with a straightforward API for request handling.
- **Scalability**: Facilitates easier updates and maintenance as our application grows.

**Suggested Implementation**:
The hook could expose functions for various HTTP methods (GET, POST, etc.) and return states indicating loading, success, and error conditions. Additionally, it could offer customization options for request headers, parameters, and other Axios configurations.

**Conclusion**:
Creating a common method for handling HTTP requests will streamline our development process and improve code maintainability. I look forward to discussing this further .

Best,
Dev Geo

**Comment by gbowne1** [comment]
@dev-george-nikolaidis 

I agree with this issue.  I also don't know if we are using axios currently in a manner that it benefits the application

A new custom hook would be fine though.

**Comment by dev-george-nikolaidis** [comment]
@gbowne1 
I can work on this.

**Comment by gbowne1** [comment]
Ok @dev-george-nikolaidis
