### ISSUE TITLE
[TODO] Constrain the blue topnav/topbar

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#23]
The blue TopNav/TopBar is now 80 or more px in height.

It needs to be constrained to around 60 to 65 px in a desktop view.

Other items in the bar may need restyled to fit the new size.

**Comment by goutham03062001** [comment]
Hello is this issue still opened?

I would like to work upon this.

**Comment by gbowne1** [comment]
I didnt close the issue.  it's open still.  @goutham03062001

**Comment by atharvarekhawar** [comment]
Hello, I would like to work on the issue can you assign it to me

**Comment by gbowne1** [comment]
Ok @atharvarekhawar

**Comment by atharvarekhawar** [comment]
![Screenshot (66)](https://github.com/gbowne1/codebooker/assets/113119063/f2b7a992-bf67-464f-a2b8-5b93b114e5e2)
![Screenshot (67)](https://github.com/gbowne1/codebooker/assets/113119063/905d12c3-adaf-4edc-a934-2edbc46bc958)

Screenshot 66 is the one with a 60px height of the topbar and 67 is with a 90px height. I don't think there is a need of resizing any element at the topbar.

**Comment by atharvarekhawar** [comment]
![Screenshot (66)](https://github.com/gbowne1/codebooker/assets/113119063/0ba082ce-3fa6-46d1-abdf-2d970d7a2219)

This is a screenshot of the website after adjusting the height of the topbar to 60px and I don't think any other element at the topbar needs resizing as everything looks perfect, I have hardcoded the height value of the topbar to 60px. If you want some changes then let me know or give me permission to create a pr.

**Comment by gbowne1** [comment]
That looks great @atharvarekhawar.  You can PR this change.
