### ISSUE TITLE
[REFACTOR] Contribution to refactor SideNav component

### ISSUE THREAD

**Issue by victor20m** [gbowne1/codebooker#24]
Hello, I'd like to contribute with a refactor to this component.

- Each list item takes about six lines of code and repeats itself for every button on the side nav, this could by simplified by creating a sub component. 

- The state management could be improved to accept future sub-categories and handle their behavior.

Cheers!

**Comment by gbowne1** [comment]
Thats fine, you are welcome to contribute.  @victor20m I noticed this too but figured it might be a bit early till we get things all set up and more components.
