### ISSUE TITLE
[TODO] Add a 200-250px Sidebar using <Drawer /> from MUI v5.11.6

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#3]
Add a 200-250px Sidebar using `<Drawer />` from MUI v5.11.6 which opens with the hamburger icon from the left.

The drawer should at least have a menu item that says Library with a MUI `<BookIcon />`   and imported with 
`import BookIcon from '@mui/icons-material/Book';`

Add the component as `<SideNav />` with SideNav.jsx and SideNav.css. in /src/components

**Comment by Yuva0** [comment]
I would like to work on this. Can you give me write access for it?
