### ISSUE TITLE
[Feat] Add book review feature

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#31]
CodeBooker should have the ability to save up to 150 word review to each book as well as add 1 to 5 ⭐ reviews.

Should be able to select a book for review and it will bring up a modal or panel

Add a review modal or panel that when you select a book to review perhaps with a review book button or checkbox.

**Comment by Vishwanath760970** [comment]
@gbowne1 I would like to get this assigned and work on this.  But, I want to understand few implementation details for UI.

Like, where do you want to place the button for book review is it along the table by creating one more column with name review book or some similar name.

![image](https://github.com/gbowne1/codebooker/assets/40589407/395578b2-2361-4e77-bcdc-19680b6de6de)

and also the review that we write once we save it and close the modal after writing the review, where do you want that review to be displayed for the respective books? 

Once we decide upon these details i can work on implementing this feature.

**Comment by gbowne1** [comment]
@Vishwanath760970 

I am totally open to ideas here, so if you have ideas we can totally discuss any ideas you have.

That being said, the path to easily reviewing a book should be easily accessible.. and at this point I will take working over looking good. We can totally iterate over styling and placement.

**Comment by Vishwanath760970** [comment]
@gbowne1 good to hear that, I have an idea of adding a column called review and added two buttons.
 1. The **review book** will open a modal to add the review for that particular book.
 2. the **read reviews** button will open a another modal, to read the reviews added for that particular book, like as in where we read google reviews for businesses.

![image](https://github.com/gbowne1/codebooker/assets/40589407/dd41946a-3b48-427e-843a-2df71a223bf8)

if this seems good to you, we can go ahead .

**Comment by gbowne1** [comment]
Yeah that seems good enough to me for a first iteration and we can see how well that works. @Vishwanath760970

**Comment by Vishwanath760970** [comment]
@gbowne1 i have developed the feature and trying to send a pull request to the main branch, after my **git commit**  i enter the next command **git push origin "branch name"** from my vs code.

But, im getting an error saying my access request is denied to the codebooker repo.

![image](https://github.com/gbowne1/codebooker/assets/40589407/c332fac8-ceab-46d6-8408-abc1a1b9d6f8)

any idea on why im facing such error?

I tried a few solutions from my end nothing seems to work, please suggest a solution if you are aware of this.

**Comment by gbowne1** [comment]
Merged as completed task @Vishwanath760970 

Thanks for your PR. :-)

**Comment by Vishwanath760970** [comment]
@gbowne1 can you please create a github issue and assign to me, to implement a feature to view the reviews added for the books that I have implemented here. That way this feature will be completed.

As discussed earlier, I will implement a modal to read the review for the users, once they click on the **Read reviews** button.

**Comment by gbowne1** [comment]
Ok I will create another issue for you.  You are welcome to open any issues

**Comment by Vishwanath760970** [comment]
@gbowne1 thank you, I want to contribute as much as possible to the project.

So, will be suggesting to open new github issues as and when required.
