### ISSUE TITLE
[Feature] Add feature to read / view the book reviews posted for each book

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#39]
Implement a feature to view the reviews added for the books that I have implemented here. That way the book review feature will be completed.

Also implement a modal to read the review for the users, once they click on the Read reviews button.

**Comment by Vishwanath760970** [comment]
@gbowne1 please assign this to me, as I'm unable to self assign.

**Comment by gbowne1** [comment]
Ok. I will assign you.
