### ISSUE TITLE
[Feature] Add a way to sort the users library table

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#40]
Currently the app has no way to sort the users' library of books in the table.

Add some sorting ability to the table columns.

**Comment by priddhesh** [comment]
On which parameter you want to sort the library table.Please ellaborate.

**Comment by gbowne1** [comment]
@priddhesh  Title, Author, Category, Publisher, Year would be the most I would expect to have sortable.

**Comment by Vishwanath760970** [comment]
@gbowne1 please assign this issue to me, I would like to work on it.

**Comment by gbowne1** [comment]
Ok @Vishwanath760970 I have assigned you.

**Comment by gbowne1** [comment]
Also implement breadcrumbs and or pagination if there are more records than the page can display and a scroll.
