### ISSUE TITLE
[Feature] Add the search functions to search bar

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#43]
Currently, if you try and use search to find a book, it doesnt work.

Needs to have the functions so that the search bar works.

**Comment by akansjain** [comment]
Hey gbowne1,
I would like to take up this issue. Please assign this issue to me.

**Comment by Mayor-Rhymes** [comment]
Hi, I think I just fixed this issue and I also eliminated the need for a search button to automate the search functionality.

**Comment by Mayor-Rhymes** [comment]
![Capture](https://github.com/gbowne1/codebooker/assets/35629340/da74e39d-15b8-4cd1-b369-4a6b151d833e)

**Comment by gbowne1** [comment]
Ok, thanks.  You can PR if you like @Mayor-Rhymes.  I will review and merge if its good.

**Comment by Mayor-Rhymes** [comment]
I just sent a PR. Thanks for the opportunity @gbowne1.

**Comment by gbowne1** [comment]
Thanks for the opportunity to review. @Mayor-Rhymes
