### ISSUE TITLE
[Bug] Adding a book with a category issue

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#46]
I found an issue where adding a book with a category field filled in like Web Development causes the category to actually be listed in "Author" column instead of the "Category" column.

**Comment by gbowne1** [comment]
@sanyam810 yes this issue still exists.

If you try adding a book with a specific category, ike say Web Development, the book will not show up listed with that category in that category column.

**Comment by LOGESH-B** [comment]
@gbowne1 
i add a book in data.json
Its looks fine
![image](https://github.com/gbowne1/codebooker/assets/86541143/9f3f1b97-77b2-444d-b4cb-fecf4c1e8028)
can you tell what needs to be done

**Comment by gbowne1** [comment]
@LOGESH-B it might work when you add to the .json but it's not working when you actually use the UI.

**Comment by LOGESH-B** [comment]
@gbowne1 
We need to make disscussion on state management!
Showing toast/alert are done easier with redux 🤷‍♂️

**Comment by gbowne1** [comment]
Yes we can have a discussion about state management.

I would prefer using what react gives us out of the box first.  We still have quite a lot to implement yet.

**Comment by gbowne1** [comment]
Oh, I forgot there already is an issue for this..  it's this issue @BlackBond06. comment so I can assign.

**Comment by BlackBond06** [comment]
Ok assign it to me.

**Comment by BlackBond06** [comment]
Hi @gbowne1 I have made a PR for this issue, please review.
