### ISSUE TITLE
[Feat] Clicking on a category in the menu drawer. the "Category should only display books from that category

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#47]
Currently opening the left side panel navigation drawer and clicking on Category, then clicking on one of the categories does not really do anything at all.

This feature of the app should display only books related to that category, so if like the user clicked on Web Development, they would be shown only books on Web Development that were added to their Library or the same in the main app view which would display all books added to the application's database.

(Note the view currently displayed is actually meant to display when the user clicks on the "Library" button in the drawer, thus showing the books in the users' own library or collection of books showing what they own.)

**Comment by LOGESH-B** [comment]
Hii @gbowne1 

I made the category select change in books.
For library we need to create a new page which is more confortable,so make it as another issue

**Comment by gbowne1** [comment]
@LOGESH-B reviewed and merged.  

5 successful merges and you could be collaborator.

**Comment by gbowne1** [comment]
@LOGESH-B one more left.  you've done 4 PR's with successful merges.  Thanks :)

**Comment by gbowne1** [comment]
@LOGESH-B 
This still doesn't really work.

I'm about ready to add the more than 200 coding/programming books to the books collection.  

I'd like to be able to click on any of the categories or subcategories on the left sidebar/sidenav and only see the books in the table that range

**Comment by LOGESH-B** [comment]
Hii @gbowne1 
Its working fine I think...if there is no matching it shows all the books..insted of showing no matching found

Look At Library.jsx 
filter function
Line No:237

**Comment by gbowne1** [comment]
Closed as completed until further notice
