### ISSUE TITLE
[TODO] Create a User Profile Page

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#50]
We do not currently have any means of users having profiles nor any means of the ability for users to create their own..

This issue is two parts:

- Create a user profile page accessible from user icon
- Create a form and methods in which the user can create their profile during their sign up or registration or account creation phase..

**Comment by LOGESH-B** [comment]
@gbowne1 
Where i need to put my backend server.The frontend and backend needs to be seperated right.
So can you create seperate folder?

**Comment by gbowne1** [comment]
Yes @LOGESH-B 

it needs a /src/server folder where the backend can exist. It can have a separate package.json to install the backend packages to.

Anyone can create the folders

**Comment by gbowne1** [comment]
Tested the backend yesterday.

Setup works pretty good.  

Now to work on login, logout, profile, etc

**Comment by LOGESH-B** [comment]
Hii @gbowne1 
* I get this error.I got this eroor while running the project then I run npm run lint:fix then after coding on Login 
* I run **npm run lint:fix** but it doesn't autofix the work
![image](https://github.com/gbowne1/codebooker/assets/86541143/5d2768fa-8bc7-494b-8626-7c22329c3137)

**Comment by gbowne1** [comment]
Ok @LOGESH-B 

The npm scripts in package.json are wrong.  I prefer using npx to run prettier and eslint.

The command for prettier is npx prettier --write .

ESLint uses    npx eslint --fix .

You can substitute . for any directory or folder.

**Comment by gbowne1** [comment]
@LOGESH-B I pushed up some updates to fix this.

**Comment by gbowne1** [comment]
Yes its quite frustrating at times which is why I stopped relying on ESLint and Prettier.  I am now using quick-lint-js with a local config.  Much less of a mess. Much better errors too.  The default ESLint that comes with create react app is not very good at all.

**Comment by gbowne1** [comment]
Note: Cleaned up comments on this issue thread reguarding the backend and are related to issues already completed.

**Comment by gbowne1** [comment]
Here is some ideas for the profile page and the rest of the app.

User information: Display the user's name, profile picture, and any other relevant details.

Bookshelf: Show the books the user has added to their bookshelf or favorites.

Reviews: Display the user's book reviews and ratings.

Recommendations: Provide personalized book recommendations based on the user's preferences and reading history.

Reading progress: Show the user's progress in reading books, such as the current page or percentage completed.

Activity feed: Display recent activity, such as books added, reviews posted, or recommendations received.

Settings: Allow the user to customize their profile settings, such as notification preferences or privacy settings.

**Comment by ratishjain12** [comment]
@gbowne1 I can build the user profile page accessible from user Icon and the form during registeration

Kindly assign it to me

**Comment by gbowne1** [comment]
Ok I will assign this to you @ratishjain12

**Comment by ratishjain12** [comment]
@gbowne1 The forms should be using material UI right?

**Comment by gbowne1** [comment]
yes @ratishjain12

**Comment by ratishjain12** [comment]
@gbowne1 what kind info I should provide in user profile?

**Comment by gbowne1** [comment]
@ratishjain12 there is a separate issue for the profile creation form used during registering after the user has logged in and registered.

I was thinking you might pick from any of these fields 

Allow a user to upload a picture or upload/select an avatar (with possible drag and drop upload)
Full Name including prefix and or suffix
Display name / Username / Nick
Location (assuming USA.. City/Town, County, State, Zip)
Age 
Date of Birth (with toggle show/hide)
Sex (Including non binary)
Ethnicity
Marital Status
Political party afiliation
Education including schools and degrees
Occupation / Career
list former workplaces
list current workplaces
Places Lived
Hometown (especially if different from current location)
Map pin (Google Maps/Google Earth)
Hobbies and Interests as tags
Photo album (Gallery) could be cards
Banner photo/background
Favorites (Color, Book(s), Movies, TV show, place, etc)
Date user joined
View count (How many times profile was viewed)
Number of Followers
Ability to share profile with Share icon button
Message and/or Chat
Follow button
Follow count
Like count
Heart/ Like / Thumbs Up / Thumbs Down
Brief biography or About (150 words or less)
Tags for Hobbies and Interests

With the option to display or not display whatever information the user wants hidden from public view..

**Comment by ratishjain12** [comment]
For this issue I have done this you can merge it,
and then I will work on that separate issue

https://github.com/gbowne1/codebooker/assets/43003421/fe898785-bcaa-43c8-822f-39fcd9757901

**Comment by gbowne1** [comment]
@ratishjain12 nice work. The PR has merge conflicts. Can you please try and resolve the merge conflicts so we can review and merge
