### ISSUE TITLE
[TODO] Logout in User Menu changes

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#57]
This user icon dropdown menu, currently under the (R) when you click on it,  needs some change.

 Logout icon (import LogoutIcon from '@mui/icons-material/Logout';) and label needs to change state to the MUI Login using this depending on the state of login/logout.

import LoginIcon from '@mui/icons-material/Login';

![Screenshot 2023-06-20 at 16-35-46 React App](https://github.com/gbowne1/codebooker/assets/47549872/073d8c0a-9b7d-47d8-a5db-1e69acc85ef8)

Note: There is no current login or logout functionality.

**Comment by gbowne1** [comment]
@LOGESH-B can we do this with useState, useEffect?

**Comment by LOGESH-B** [comment]
@gbowne1  I am not clearly getting you

with my understanding we can store the login details in local storage along with cookie so we can fetch from there to verify the login/logout state of a user

**Comment by gbowne1** [comment]
The icon and its label "Logout" as I showed above should change state between when user is logged in or logged out.  I believe its possible to change this in the view depending on state.

**Comment by LOGESH-B** [comment]
Yeah we can chage it by state using this


> @gbowne1 I am not clearly getting you
> 
> with my understanding we can store the login details in local storage along with cookie so we can fetch from there to verify the login/logout state of a user

**Comment by gbowne1** [comment]
Ok.  We will need to both authorize and authenticate as well.  Are we storing auth stuff in the db for validation?  I would like to make use of what the browser gives us too like localStorage, indexedDB, session, cookies, etc so as long as it can be done securely.

**Comment by LOGESH-B** [comment]
@gbowne1 
Yeah we can use localstorage or cookie but I am suggesting to use the JWT tokens....during login we can geneate the JWT token and store it in local storage for each req we can send it as header for the validation of the user

**Comment by gbowne1** [comment]
yeah we can definitely use JWT's, get the tokens and save it to storage with maybe a utility.

I made a PR with changes to implement the Login UI and also the icon changing in this issue.

**Comment by gbowne1** [comment]
I think it would be better to use Session storage as it is a better option than local storage for storing sensitive information as it is cleared when the session ends and perhaps some cookies.

**Comment by LOGESH-B** [comment]
> I think it would be better to use Session storage as it is a better option than local storage for storing sensitive information as it is cleared when the session ends and perhaps some cookies.

Ok it is also a good idea✌️

**Comment by gbowne1** [comment]
I mean not that its a good or bad idea to use local and we can test it for development purposes, but yeah, if someone happens to catch the xss, xhr, etc. when in production, not gonna be that good.
