### ISSUE TITLE
[TODO] Remove the other categories from sidenav panel/drawer

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#59]
The only category that should exist is the category Languages.

The ones that should be removed are
Education

Also, each language, should get it's own menu/nav button in the left sidebar/sidenav drawer.  

Choosing a language or in the nav should only display the items in that category.

**Comment by JunioDo** [comment]
Hi Gregory,
I'm a fullstack developer with 5 years of experience.
I came across the repository issues on Github by chance.
I'm looking into your repository projects and would like to contribute your projects as a freelancer.
Could you tell me about this project?

**Comment by gbowne1** [comment]
The README.md should explain the project.  If it does not, I can change that.

I welcome contributors and contributions  to any of my projects.  Feel free to explore my projects.

This one is not an ecommerce app.  It is a book recommendation and review platform specifically for coding and programming books only.

**Comment by JunioDo** [comment]
Can you give me a budget or salary for my works?

**Comment by gbowne1** [comment]
This is not a paid project @JunioDo

**Comment by LOGESH-B** [comment]
@gbowne1 
Hi @gbowne1,
Is this what you are expecting, the change in UI?
![image](https://github.com/gbowne1/codebooker/assets/86541143/5d6a0333-e45d-4892-a015-1005bb06faf4)

**Comment by gbowne1** [comment]
@LOGESH-B yes, that is correct, but remove 'Psychology' as well.

**Comment by LOGESH-B** [comment]
> @LOGESH-B yes, that is correct, but remove 'Psychology' as well.

@gbowne1  I removed and raised the PR #61

**Comment by gbowne1** [comment]
Thanks @LOGESH-B will review and merge if it tests out good.
