### ISSUE TITLE
[TODO] Add an Add to Library button

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#63]
There should be a method to add or remove the books listed in the "global" scope to the users library and from the users "library", which would be seen if the user clicks on Library in the sidenav.  Clicking on the Category they want to choose in the sidenav should display the global library by category.. later on this could be expanded upon.

While the books listed in the current view could be considered the global library, they should also be duplicated in both the global and library scope when the user(s) add books to their library.. at the very least the duplicated would happen if the book the user is adding to their library isn't in the database. If it is in the database already then it would only be added to the users "library".

So the task at hand would be to start building out what would appear when the user clicks on "Library"in the sidenav.

**Comment by dev-george-nikolaidis** [comment]
Hi @gbowne1, can I work on this task?

**Comment by gbowne1** [comment]
Sure @dev-george-nikolaidis I will assign you

**Comment by dev-george-nikolaidis** [comment]
@gbowne1 So the task is to add an extra global category on the side nav that will contain the exact data as the data fetched on the home page. Did I get that correct?

![CodeBooker](https://github.com/gbowne1/codebooker/assets/82717511/5691ec9a-1efe-4e78-aeff-857b26651ecb)

**Comment by gbowne1** [comment]
@dev-george-nikolaidis 

Almost. I agree there should be a global library. There should be two libraries a user based library. and a global library that displays all books users have added.

The user could potentially share their library and recommended reading lists for a number of programming subjects aka on React Social Media site or Facebook, etc.

However I was trying to get the app to be able to display whatever programming books the user has in their personal library plus be able to add programming books to a global library 

As well as be able to rate books and maybe later on add a forum where people can discuss the books, post bug reports on the code in the book, etc.

The table youre seeing in the app now is not a global library Its supposed to be a users library.

The add to library needs to be on the individual rows near the blue and green buttons at the right end of the rows.

The UI really needs to be redone.

There also needs to be a method so the user like me who has hundreds of programming books to add them via a serial or usb barcode scanner wand.

Also the cover images need to display some where when the user clicks on any book 

Later on we could add a method to add .zip and .tar.gz the code

**Comment by gbowne1** [comment]
The add to library button should be next to the green and blue buttons labeled read reviews and review book on the right of every row in the table. This button should add the book from the users library to the global library and it could also add it from the global library to the users library dependent on how its set up. It may even bring up some sort of popup, modal, alert, toast, dialog that lets the user select which context to add the book to.  And if the book is already in the users library and not in the global library or not in the users library but in the global library dependent on what the user selected
