### ISSUE TITLE
[Bug]  Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#64]
in the app I get this message in the browser console:

Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SideNav`. See https://reactjs.org/link/warning-keys for more information.
MenuButton@http://localhost:3000/static/js/bundle.js:2063:9
SideNav@http://localhost:3000/static/js/bundle.js:2048:90
div
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
Toolbar@http://localhost:3000/static/js/bundle.js:24484:82
header
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
Paper@http://localhost:3000/static/js/bundle.js:19183:83
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
AppBar@http://localhost:3000/static/js/bundle.js:7949:83
div
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
Box@http://localhost:3000/static/js/bundle.js:28934:72
div
ThemeProvider@http://localhost:3000/static/js/bundle.js:27768:7
ThemeProvider@http://localhost:3000/static/js/bundle.js:28154:7
ThemeProvider@http://localhost:3000/static/js/bundle.js:26350:9
App@http://localhost:3000/static/js/bundle.js:161:74 line 3 > eval:1:8345

**Comment by Piyush-Deshmukh** [comment]
**Hey there, can you assign me this issue while providing me more information on the issue ?**


- The issue may have occured due to the missing key prop in SideNav.jsx.

![image](https://github.com/gbowne1/codebooker/assets/99667276/f1b7da9a-4650-42c8-9aa6-25f8e4faa5d2)

**Comment by gbowne1** [comment]
@Piyush-Deshmukh I don't have any other information other than what appears in the console of the browser.
