### ISSUE TITLE
[BUG]  React does not recognize the `autoHideDuration` prop on a DOM element.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#65]
I get this warning in the browser console:

Warning: React does not recognize the `autoHideDuration` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `autohideduration` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
button
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
ButtonBase@http://localhost:3000/static/js/bundle.js:9184:82
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
IconButton@http://localhost:3000/static/js/bundle.js:14466:83
div
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
div
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
Paper@http://localhost:3000/static/js/bundle.js:19183:83
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
SnackbarContent@http://localhost:3000/static/js/bundle.js:21943:83
Transition@http://localhost:3000/static/js/bundle.js:86836:30
Grow@http://localhost:3000/static/js/bundle.js:14126:9
div
./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js/withEmotionCache/<@http://localhost:3000/static/js/bundle.js:3330:66
ClickAwayListener@http://localhost:3000/static/js/bundle.js:4786:7
Snackbar@http://localhost:3000/static/js/bundle.js:21592:82
Library@http://localhost:3000/main.773e53579ed5e8f5cca4.hot-update.js:123:7
div
ThemeProvider@http://localhost:3000/static/js/bundle.js:27768:7
ThemeProvider@http://localhost:3000/static/js/bundle.js:28154:7
ThemeProvider@http://localhost:3000/static/js/bundle.js:26350:9
App@http://localhost:3000/main.15b74a8356090f883ade.hot-update.js:112:74

**Comment by Joywin2412** [comment]
Heyy! I'm not sure what that error is! But I have decent experience in react. Please assign me this issue!

**Comment by gbowne1** [comment]
I want able to figure this one out.  You're welcome to work on it

**Comment by Joywin2412** [comment]
I'm having trouble finding how to reproduce this issue. I tried some of the features but wasn't able to get the error. Could you share a screenshot or a method on how to reproduce this issue?

**Comment by gbowne1** [comment]
@Joywin2412 I don't know.  This appears in the browser console at least on my machine.  I put the issue up in case anyone had an idea what's causing it.  If it's not there not sure what was causing it. The other error was fixed address by fixing a key.

**Comment by Joywin2412** [comment]
Error1 : Warning: validateDOMNesting(...): <h6> cannot appear as a descendant of <p>.  Happens:When clicking on read reviews.
Error2: react-jsx-dev-runtime.development.js:87 Warning: Failed prop type: Invalid prop `direction` of value `dsc` supplied to `ForwardRef(TableSortLabel)`, expected one of ["asc","desc"]. Happens: When clicking on sorting arrow on the homepage

These are the only two errors I encountered myself on my machine. Could you verify these are the same errors that occurs on your machine too? @gbowne1

**Comment by Joywin2412** [comment]
1)validateDOMNesting(...): <h6> cannot appear as a descendant of <p>.
This happens when clicking on READ REVIEWS button
2)Invalid prop `direction` of value `dsc` supplied to `ForwardRef(TableSortLabel)`, expected one of ["asc","desc"].
This happens on clicking the arrow to sort the list of books

These are the only two errors I encountered. Do you encounter the same errors @gbowne1 ?

**Comment by Joywin2412** [comment]
1)validateDomNesting
This happens when clicking on READ REVIEWS button
2)Invalid prop direction 
This happens on clicking the arrow to sort the list of books

These are the only two errors I encountered. Do you encounter the same errors @gbowne1 ?

**Comment by gbowne1** [comment]
Yes @Joywin2412 this one does exist on my machine.  I just hadn't issued the bug report for that.

I did try on both Chrome and Firefox.

There is not much of a backend on this app.  I did make an issue for that.

**Comment by Joywin2412** [comment]
It seems though I can't reproduce the issue. If someone else is able to reproduce the issue then they could solve it. So I think I'll unassign myself.

**Comment by gbowne1** [comment]
There's plenty to work on though.  I will check tomorrow when I return.

I have a bunch of react apps that need a lot of work too.

**Comment by gbowne1** [comment]
as far as I can tell, this issue does not exist anymore @Joywin2412

I will be making some other issues today.
