### ISSUE TITLE
[TODO] Frameworks & Libraries category needs individual tabs in the nav for the frameworks and libraries

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#71]
Clicking on the hamburger icon opens the left sidenav.  Clicking on the "Category" tab, then clicking on the "Frameworks & Libraries" tab opens two separate tabs that have multple frameworks and libraries in one tab.  

This should be separated out into tabs for each individual Framework and Library like React, Vue, Angular, etc.  The same for DevOps.

**Comment by shivm29** [comment]
Hey @gbowne1 ! I think I can help. please assign me this
