### ISSUE TITLE
[TODO] Add eslint and prettier and their configurations 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#77]
This project is missing ESLint and Prettier and their configurations so that the code can be more uniform and maintainable.

These packages need to be installed as devDependencies:

eslint-config-prettier
eslint-plugin-react
eslint-plugin-prettier

.prettierrc and .eslintrc rules need to be added, especially for singleQuote="true".

[ESLint Config](https://eslint.org/docs/latest/use/configure/)
[Prettier Config](https://prettier.io/docs/en/configuration.html)

Prettier and ESLint packages should also be installed as devDependencies along with the plugin and config packages

**Comment by kabszac** [comment]
hi, is there any specific style guides we are supposed to use with the eslint?

**Comment by gbowne1** [comment]
@kabszac 

Prettier
```json
{ "jsxSingleQuote": true, "singleQuote": true }
```
ESlint
```json
{ "rules": { "jsx-quotes": ["error", "prefer-single"], "quotes": ["error", "single"] } }
```

**Comment by kabszac** [comment]
ok could I be assigned this issue

**Comment by gbowne1** [comment]
Ok, @kabszac
