### ISSUE TITLE
[TODO][A11y] Accessibility/A11y testing

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#78]
According to at least using the Firefox browser Accessibility test, we have the following problems:

-  Clickable elements must be focusable and should have interactive semantics
-  Focusable element may be missing focus styling. 
-  Form elements should have a visible text label. 

There are also keyboard, contrast and text label issues.

**Comment by Jonnie-Dev** [comment]
Hi, can I work on this?

**Comment by gbowne1** [comment]
Sure @Jonnie-Dev
