### ISSUE TITLE
[TODO][BUG] Remove unused imports from the codebase

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#91]
I overengineered the App.js, thinking I needed to add things to get ahead of imports we might need, and a few other files and imported too many Material UI a.k.a @mui imports. which now show up in ESLint as 'is defined but never used'  no-unused-vars.

Remove all the unused imports from App.js that do not appear in the actual code.

**Comment by neeravbhaskarla** [comment]
can i get this issue assigned?

**Comment by gbowne1** [comment]
ok @neeravbhaskarla
